//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayonetWpfApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KnifeDBEntities : DbContext
    {
        public KnifeDBEntities()
            : base("name=KnifeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Achievement> Achievement { get; set; }
        public DbSet<EventType> EventType { get; set; }
        public DbSet<Gender> Gender { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Schedule> Schedule { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserAchievement> UserAchievement { get; set; }
    }
}
