//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayonetWpfApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleId { get; set; }
        public Nullable<int> EventTypeId { get; set; }
        public System.DateTime EventDate { get; set; }
        public string EventName { get; set; }
        public Nullable<int> idNews { get; set; }
        public Nullable<int> idUser { get; set; }
        public int id { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual News News { get; set; }
        public virtual User User { get; set; }
    }
}
