//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayonetWpfApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Schedule = new HashSet<Schedule>();
            this.UserAchievement = new HashSet<UserAchievement>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> GenderId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual ICollection<UserAchievement> UserAchievement { get; set; }
    }
}
