//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayonetWpfApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAchievement
    {
        public int UserId { get; set; }
        public int AchievementId { get; set; }
        public Nullable<System.DateTime> AchievementDate { get; set; }
    
        public virtual Achievement Achievement { get; set; }
        public virtual User User { get; set; }
    }
}
